#### Знакомство с библиотекой NumPy

Кудрявцев Николай Михайлович.
КИ19-09Б, 031940750

NumPy — библиотека для работы с многомерными массивами и математических вычислений различного рода.  
NumPy можно рассматривать как некую альтернативу MATLAB.  
   
[Документация NumPy](https://numpy.org/doc/stable/reference/index.html)

**Импорт библиотеки NumPy:**

In [3]:
import numpy as np
import random

**Создание одномерного массива:**

In [181]:
array_1D = np.array([1, 0, 2, 3])

**Вывод массива для ознакомления:**

In [182]:
array_1D

array([1, 0, 2, 3])

**Создание двумерного массива:**


In [183]:
array_2D = np.array([[1, 0, 2], [3, 4, 5], [6, 8, 7], [12, 22, 9]])
array_2D

array([[ 1,  0,  2],
       [ 3,  4,  5],
       [ 6,  8,  7],
       [12, 22,  9]])

**Просмотр типа данных элементов массива:**

In [184]:
array_2D.dtype

dtype('int32')

**Тип данных можно задать при создании массива:**

In [185]:
array_int32 = np.array([1], dtype = np.float)
print(array_int32.dtype, "- тип данных")
print(array_int32, "- значение переменных массива")

float64 - тип данных
[1.] - значение переменных массива


C:\Users\413\AppData\Local\Temp\ipykernel_17672\2301629707.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_int32 = np.array([1], dtype = np.float)


**Вывод размерности массива:**

In [186]:
print(array_1D.shape, "- количество элементов одномерного массива")
print(array_2D.shape, "- количество строк и столбцов двумерного массива")

print(array_1D.size, "- количество элементов одномерного массива")
print(array_2D.size, "- количество элементов двумерно массива")

(4,) - количество элементов одномерного массива
(4, 3) - количество строк и столбцов двумерного массива
4 - количество элементов одномерного массива
12 - количество элементов двумерно массива


**Варианты автоматического заполнения массивов:**

In [187]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [188]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [189]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [190]:
np.random.random((2, 4))

array([[0.0288164 , 0.50409106, 0.62960086, 0.15183021],
       [0.6894392 , 0.97827303, 0.43237745, 0.09378745]])

In [191]:
np.full((2, 2), 5)

array([[5, 5],
       [5, 5]])

In [192]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**Обращение к элементу массива по его индексу:**  
*(индексация начинается с нуля)*

In [193]:
print(array_1D)
array_1D[1]

[1 0 2 3]


0

In [194]:
print(array_2D)
array_2D[1, 2]

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


5

In [195]:
print(array_2D[:, :])
array_2D[:2, :3]

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


array([[1, 0, 2],
       [3, 4, 5]])

In [196]:
np.argmax(array_1D) # индекс максимального элемента массива
array_1D[np.argmax(array_1D)]

3

**Просмотр элементов массива, удовлетворяющих условию:**

In [197]:
array_2D > 5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [198]:
array_2D[array_2D > 5]

array([ 6,  8,  7, 12, 22,  9])

**Изменение размерности матрицы:**

In [199]:
print(array_2D)
array_2D.flatten()

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


array([ 1,  0,  2,  3,  4,  5,  6,  8,  7, 12, 22,  9])

In [200]:
print(array_2D)
array_2D.reshape(6,2)

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


array([[ 1,  0],
       [ 2,  3],
       [ 4,  5],
       [ 6,  8],
       [ 7, 12],
       [22,  9]])

In [201]:
# Метод resize() изменяет размерность массива и перезаписывает его
print(array_2D)
array_2D.resize(2, 6)
array_2D

[[ 1  0  2]
 [ 3  4  5]
 [ 6  8  7]
 [12 22  9]]


array([[ 1,  0,  2,  3,  4,  5],
       [ 6,  8,  7, 12, 22,  9]])

**Арифметические действия с массивами:**

In [202]:
a = np.array([1, 2])
b = np.array([2, 3])

In [203]:
# сложение
print(a + b, '\n')
print(np.add(a, b))

[3 5] 

[3 5]


In [204]:
# вычитание
print(a - b, '\n')
print(np.subtract(a, b))

[-1 -1] 

[-1 -1]


In [205]:
# деление
print(a / b, '\n')
print(np.divide(a, b))

[0.5        0.66666667] 

[0.5        0.66666667]


In [206]:
# поэлементное умножение
print(a * b, '\n')
print(np.multiply(a, b))

[2 6] 

[2 6]


**Скалярное произведение векторов, умножение матриц:**

In [207]:
a = np.array([2, 3])
b = np.array([[4], [5]])

In [208]:
print(np.dot(a, b), '\n')
print(a @ b)

[23] 

[23]


In [209]:
print(np.dot(a, 3), '\n')
print(a * 3)

[6 9] 

[6 9]


**Суммирование элементов массива:**

In [210]:
a = np.array([1, 2, 3])
np.sum(a)

6

In [211]:
a = a * 2.0 # изменение типа элементов массива на float
print(a)
np.sum(a, dtype = np.int64) # суммирование элементов массива и приведение к типу int

[2. 4. 6.]


12

In [212]:
# сумма элементов по столбцам
a = np.array([[4, 5, 6], [2, 3, 4]])
np.sum(a, axis = 0)

array([ 6,  8, 10])

In [213]:
# сумма элементов по строкам
np.sum(a, axis = 1)

array([15,  9])

**Модуль каждого элемента массива:**

In [214]:
a = np.array([-2, 3, -4])
print(np.abs(a)) # возвращает модуль того же типа, что и исходный массив
print(np.fabs(a)) # возвращает модуль типа float


[2 3 4]
[2. 3. 4.]


**Объединение массивов:**

In [215]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [216]:
print(np.stack((a, b)))
print()
print(np.stack((a, b), axis = 1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


**Разделение массивов:**

In [217]:
a = np.arange(5)
c = np.array_split(a, 3)
print(c[0])
print(c[1])
print(c[2])

[0 1]
[2 3]
[4]


**Другие действия с массивами:**

In [218]:
# подсчет количества вхождений каждого элемента массива
a = np.array([0, 1, 2, 2, 1, 1, 3, 3, 3, 4]) 
np.bincount(a)

array([1, 3, 2, 3, 1], dtype=int64)

In [219]:
a = np.random.randint(1, 10, 10) 
print(a)
np.argpartition(a, kth = 3) # сортирует kth-ый элемент массива, 
                            # значения меньше kth-ого элемента будут расположены слева от него, 
                            # а больше - справа в произвольном порядке. Функция возвращает ИНДЕКСЫ элементов.

[9 5 5 5 8 1 8 8 3 8]


array([5, 8, 3, 2, 1, 4, 9, 7, 6, 0], dtype=int64)

In [220]:
# удаление строк или столбцов матрицы
np.arange(4, 6, 1)
a = np.array([np.arange(3), np.arange(3,6)])
print(a, "\n")
print(np.delete(a, 1, axis = 1)) # удаление второго столбца
print()
print(np.delete(a, 0, axis = 0)) # удаление первой строки

[[0 1 2]
 [3 4 5]] 

[[0 2]
 [3 5]]

[[3 4 5]]


# Задачи для самостоятельного решения  
---

**1. Создать одномерный массив, заполненный двойками, но 6-ой элемент равен 8**

In [260]:
array_A = np.full((1, 8), 2)
array_A[0,6] = 8
array_A

array([[2, 2, 2, 2, 2, 2, 8, 2]])

**2. Создать одномерный массив, со значениями от 15 до 98**

In [261]:
array_B = np.random.randint(15, 98, 5)
array_B

array([41, 30, 93, 74, 95])

**3. Перевернуть вектор  
*(123 -> 321)***

In [262]:
array_C = np.array([1, 2, 3])
reversed_array_C = array_C[::-1]
reversed_array_C

array([3, 2, 1])

**4. Найти минимальный и максимальный элемент двумерного массива размерностью 15х15**

In [265]:
# Двумерный массив 15х15
array_D = np.random.randint(100, size=(15, 15))
array_D

array([[64, 23, 42,  3, 73, 71, 42, 63, 60, 19, 86, 70, 37, 83,  1],
       [69, 50, 93, 47, 41, 18, 90, 64, 65, 54, 26, 50, 29, 10, 10],
       [ 9, 77, 93, 12, 58, 10, 86, 30, 40, 11,  1, 42, 13, 85, 78],
       [83, 71, 66, 31, 90, 87, 48, 91, 55, 54, 59, 71,  4, 68,  3],
       [24, 19, 33, 80, 78, 47, 92, 98, 44, 23, 80, 18, 64, 52, 59],
       [11, 70, 78, 33, 94, 40, 98, 32, 91, 28, 23,  4, 33, 91, 90],
       [79, 58, 30, 64, 90, 61, 46, 96,  8, 47, 21, 37, 86, 96, 20],
       [45, 61,  6,  5, 89, 84,  2,  1, 41, 41, 79,  6, 55, 96, 58],
       [44, 51, 42,  1, 61, 72, 94, 68, 70, 35, 60, 62,  0,  9, 22],
       [39, 43,  3, 27, 84, 91, 94, 64, 23, 82,  2, 48, 14, 74, 19],
       [49, 47, 82, 39, 30, 81, 73, 85, 63, 94, 89, 98, 21,  9, 51],
       [97, 81, 56, 48, 56, 51, 36, 28, 71,  1, 62, 32, 72, 83, 74],
       [ 3, 42, 56, 41, 36, 34, 75, 26, 68, 86, 34, 60, 52, 47, 71],
       [55, 39, 86, 34, 68, 84, 80, 52, 21, 81, 90, 15, 24, 47, 46],
       [ 2, 73, 53, 25, 22, 71, 62

In [266]:
# Минимальный и максимальный элементы
min = np.min(array_D)
max = np.max(array_D)
minmax = np.array([min, max])
minmax

array([ 0, 98])

**5. Поменять в двумерном массиве 3 и 4 строку между собой**

In [269]:
# Двумерный массив
array_E = np.random.randint(99, size=(5, 3))
array_E

array([[65, 76, 39],
       [67, 70, 63],
       [91, 59, 22],
       [42, 40,  7],
       [74, 20, 37]])

In [270]:
# Двумерный массив (строки 3 и 4 поменяли)
array_E[[3, 4]] = array_E[[4, 3]]
array_E

array([[65, 76, 39],
       [67, 70, 63],
       [91, 59, 22],
       [74, 20, 37],
       [42, 40,  7]])

**6. Поменять каждый 4-ый элемент в одномерном массиве на заданное число: 212**

In [4]:
# Массив
array_F = np.random.randint(1, 50, 10)
array_F

array([ 3, 31, 46, 20, 44, 49, 10, 26,  5, 35])

In [5]:
# Массив после замены элементов
s = array_F.size
array_F[3::4]=212
    
array_F

array([  3,  31,  46, 212,  44,  49,  10, 212,   5,  35])

**7. Используя циклы написать собственную реализацию умножения двух двумерных матриц, засечь время выполнения и сравнить его с функцией умножения матриц NumPy:**

In [21]:
n = 9
A = np.random.rand(n, n)

# Округляем до 3х знаков после запятой
A_array = np.array(A)
round_A = np.around(A_array, 3)
round_A

array([[0.342, 0.874, 0.662, 0.544, 0.633, 0.001, 0.284, 0.197, 0.003],
       [0.838, 0.112, 0.081, 0.592, 0.505, 0.166, 0.024, 0.928, 0.673],
       [0.052, 0.2  , 0.371, 0.264, 0.284, 0.838, 0.321, 0.861, 0.031],
       [0.165, 0.549, 0.629, 0.016, 0.731, 0.495, 0.868, 0.963, 0.614],
       [0.759, 0.017, 0.923, 0.107, 0.836, 0.123, 0.917, 0.145, 0.118],
       [0.436, 0.343, 0.29 , 0.862, 0.003, 0.623, 0.481, 0.547, 0.999],
       [0.78 , 0.715, 0.704, 0.779, 0.202, 0.127, 0.734, 0.986, 0.663],
       [0.556, 0.183, 0.98 , 0.639, 0.751, 0.059, 0.131, 0.762, 0.787],
       [0.757, 0.46 , 0.702, 0.412, 0.58 , 0.742, 0.951, 0.354, 0.721]])

In [22]:
B = np.random.rand(n, n)

# Округляем до 3х знаков после запятой
B_array = np.array(B)
round_B = np.around(B_array, 3)
round_B

array([[0.299, 0.082, 0.937, 0.709, 0.305, 0.907, 0.835, 0.861, 0.066],
       [0.659, 0.224, 0.034, 0.95 , 0.86 , 0.895, 0.96 , 0.052, 0.084],
       [0.935, 0.877, 0.285, 0.344, 0.755, 0.683, 0.764, 0.136, 0.964],
       [0.709, 0.097, 0.212, 0.732, 0.192, 0.226, 0.254, 0.045, 0.961],
       [0.421, 0.227, 0.352, 0.273, 0.245, 0.952, 0.534, 0.994, 0.639],
       [0.796, 0.358, 0.327, 0.84 , 0.265, 0.379, 0.574, 0.562, 0.263],
       [0.998, 0.527, 0.897, 0.031, 0.985, 0.112, 0.812, 0.721, 0.323],
       [0.956, 0.181, 0.841, 0.965, 0.448, 0.84 , 0.404, 0.597, 0.891],
       [0.835, 0.343, 0.961, 0.222, 0.447, 0.955, 0.195, 0.379, 0.962]])

In [23]:
%%time
C = A @ B

CPU times: total: 0 ns
Wall time: 0 ns


In [24]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] +=  A[i, k] * B[k, j]

# Округляем до 3х знаков после запятой
C_array = np.array(C)
round_C = np.around(C_array, 3)
round_C

CPU times: total: 0 ns
Wall time: 997 µs


array([[2.425, 1.187, 1.3  , 2.072, 1.985, 2.47 , 2.418, 1.408, 1.932],
       [2.64 , 0.808, 2.62 , 2.486, 1.436, 3.019, 1.912, 2.188, 2.562],
       [2.638, 1.099, 1.633, 2.176, 1.526, 1.916, 1.833, 1.628, 1.934],
       [4.012, 1.874, 2.953, 2.574, 2.872, 3.45 , 3.038, 2.696, 3.004],
       [2.78 , 1.67 , 2.39 , 1.476, 2.223, 2.538, 2.726, 2.477, 2.15 ],
       [3.574, 1.369, 2.743, 2.654, 2.144, 2.802, 2.3  , 1.877, 2.936],
       [4.331, 1.801, 3.358, 3.328, 3.078, 3.788, 3.378, 2.481, 3.455],
       [3.536, 1.676, 2.74 , 2.541, 2.211, 3.624, 2.553, 2.277, 3.584],
       [4.202, 2.029, 3.302, 2.83 , 2.991, 3.596, 3.506, 2.954, 3.043]])